DROP DATABASE IF EXISTS employee;
CREATE DATABASE employee;
USE employee;




CREATE TABLE department(
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE role(
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(30) NOT NULL UNIQUE,
    salary DECIMAL NOT NULL,
    department_id INT NOT NULL
);

CREATE TABLE employee(
    id INT PRIMARY KEY AUTO_INCREMENT,
    first_name VARCHAR(30) NOT NULL,
    last_name VARCHAR(30) NOT NULL,
    role_id INT NOT NULL,
    manager_id INT
);